In [15]:
import open3d as o3d
import numpy as np
import torch

In [7]:
mesh = o3d.io.read_triangle_mesh("mesh/0.ply")

In [8]:
mesh.triangles

std::vector<Eigen::Vector3i> with 112416 elements.
Use numpy.asarray() to access data.

In [15]:
vertices = np.asarray(mesh.vertices)
triangles = np.asarray(mesh.triangles)

In [14]:
vertices.shape

(56470, 3)

In [17]:
triangles[:10, :]

array([[ 2,  1,  0],
       [ 3,  0,  1],
       [ 6,  5,  4],
       [ 7,  4,  5],
       [ 8,  2,  0],
       [ 8,  0,  3],
       [ 9,  6,  4],
       [ 9,  4,  7],
       [12, 11, 10],
       [14, 13, 10]], dtype=int32)

In [10]:
o3d.visualization.draw_geometries([mesh])

In [11]:
type(mesh)

open3d.cuda.pybind.geometry.TriangleMesh

In [ ]:
mesh_new = o3d.geometry.TriangleMesh()
mesh_new.vertices

In [19]:
volume = o3d.pipelines.integration.ScalableTSDFVolume(
    voxel_length=4.0 / 512.0,
    sdf_trunc=0.04,
    color_type=o3d.pipelines.integration.TSDFVolumeColorType.RGB8)

In [ ]:
volume.extract_triangle_mesh()

In [37]:
xx, yy, zz = torch.meshgrid(
    torch.arange(10),
    torch.arange(20),
    torch.arange(30)
)

In [50]:
coords = torch.cat([
    xx.reshape(1, -1),
    yy.reshape(1, -1),
    zz.reshape(1, -1)
], dim=0).int().T

In [51]:
coords[10]

tensor([ 0,  0, 10], dtype=torch.int32)

In [56]:
coords.cuda()

tensor([[ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  0,  2],
        ...,
        [ 9, 19, 27],
        [ 9, 19, 28],
        [ 9, 19, 29]], device='cuda:0', dtype=torch.int32)

In [53]:
torch.cuda.is_available()

True

In [26]:
coords_homo = torch.from_numpy(coords)
coords_homo = torch.cat([coords_homo, torch.ones(coords.shape[0]).unsqueeze(-1)], 1) 

In [27]:
coords_homo.shape

torch.Size([6000, 4])

In [28]:
coords_homo

tensor([[ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  1.],
        [ 0.,  0.,  2.,  1.],
        ...,
        [ 9., 19., 27.,  1.],
        [ 9., 19., 28.,  1.],
        [ 9., 19., 29.,  1.]])

In [33]:
T = torch.eye(4)
T[3,0] = 1

In [34]:
coords_homo @ T

tensor([[ 1.,  0.,  0.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  2.,  1.],
        ...,
        [10., 19., 27.,  1.],
        [10., 19., 28.,  1.],
        [10., 19., 29.,  1.]])